### PR TITLE
change direct message icon

### PR DESCRIPTION
**Pull request by milkknife**
sample

yes/no? thoughts?
to me it still looks like a placeholder icon, but a slightly nicer

### CODE REVIEW

**Comment by TheK0tYaRa** [comment]
Seems too flat, may confuse Discord's law speakers into DMCA

**Comment by diamondburned** [comment]
OK, I'm not sure why the DM icon is a green circle on your screen. Perhaps we need to embed an SVG.

It should look like this:

image

**Comment by diamondburned** [comment]
Relying on the icon theme doesn't seem like the best idea.

**Comment by milkknife** [comment]
image
b6fc6e64-db68-40f9-bb94-e841d10583ff

Currently it's a status icon for when a user is available, and it's different across icon themes. Default Adwaita has the speech bubble, but it's huge. What icon theme are you using?

**Comment by diamondburned** [comment]
> What icon theme are you using?

I'm using Papirus.

**Comment by milkknife** [comment]
image
b908c49bf1942f74413979687fb45d8d34f2db09 ^^^

I will also look into https://fonts.google.com/icons?icon.style=Rounded&icon.query=message

**Comment by diamondburned** [comment]
Hmm, I can't seem to get the CI to run.

**Comment by milkknife** [comment]
this is how it looks currently (39487c82f2849b5cdcbdb4794bef3597cc92fa84):
sample2
(themes from left to right: Dracula, Adwaita, Adwaita-dark)
(with libadwaita compiled) 
- changes dark/light depending on gtk theme
- icon for dark theme is `#DEDEDE`
- icon for light theme is `#2E3436`

**Comment by diamondburned** [comment]
I think it looks a bit too big.

**Comment by diamondburned** [comment]
Can you apply this diff?

```diff
diff --git a/internal/gtkcord/sidebar/directbutton/button.go b/internal/gtkcord/sidebar/directbutton/button.go
index 44a6c08..2812e0f 100644
--- a/internal/gtkcord/sidebar/directbutton/button.go
+++ b/internal/gtkcord/sidebar/directbutton/button.go
@@ -2,6 +2,7 @@ package directbutton
 
 import (
        "context"
+       "math"
 
        "github.com/diamondburned/gotk4/pkg/gtk/v4"
        "github.com/diamondburned/gotkit/gtkutil/cssutil"
@@ -23,6 +24,10 @@ var dmButtonCSS = cssutil.Applier("sidebar-dm-button-overlay", `
                padding: 4px 12px;
                border-radius: 0;
        }
+       .sidebar-dm-button image {
+               padding-top: 4px;
+               padding-bottom: 2px;
+       }
 `)
 
 func NewButton(ctx context.Context, open func()) *Button {
@@ -30,7 +35,7 @@ func NewButton(ctx context.Context, open func()) *Button {
 
        icon := gtk.NewImageFromPixbuf(icons.Pixbuf("dm"))
        icon.SetIconSize(gtk.IconSizeLarge)
-       icon.SetPixelSize(gtkcord.GuildIconSize)
+       icon.SetPixelSize(int(math.Round(gtkcord.GuildIconSize * 0.85)))
 
        b.Button = gtk.NewButton()
        b.Button.AddCSSClass("sidebar-dm-button")
diff --git a/internal/gtkcord/sidebar/guilds/guilds.go b/internal/gtkcord/sidebar/guilds/guilds.go
index 16bdd67..b0db65a 100644
--- a/internal/gtkcord/sidebar/guilds/guilds.go
+++ b/internal/gtkcord/sidebar/guilds/guilds.go
@@ -54,6 +54,9 @@ type currentGuild struct {
 }
 
 var viewCSS = cssutil.Applier("guild-view", `
+       .guild-view {
+               margin: 4px 0;
+       }
        .guild-view button:active:not(:hover) {
                background: initial;
        }
```

**Comment by TheK0tYaRa** [comment]
Why add margin if you can lower the size of parent

**Comment by diamondburned** [comment]
> Why add margin if you can lower the size of parent

What do you mean? The margins are vertical. The point of margins is to add empty space, and lowering the size doesn't always do that.

**Comment by TheK0tYaRa** [comment]
Adding empty space is adding unused space.

**Review by diamondburned — APPROVED** [review]

**Pull request merged**
