### PR TITLE
Add emoji button to composer

### PR DESCRIPTION
**Pull request by tfuxu**
This PR adds an emoji menu button to composer, which shows [`gtk.EmojiChooser`](https://docs.gtk.org/gtk4/class.EmojiChooser.html) when clicked.

Screenshot:
Screenshot from 2023-09-30 15-05-15

### CODE REVIEW

**Comment by diamondburned** [comment]
There are slight issues with this:

1. How would this look on mobile? Especially when replying, there will be 4 buttons down there!
2. How about custom emojis? Shouldn't that also be accounted for?

**Comment by tfuxu** [comment]
> There are slight issues with this:
> 
>     1. How would this look on mobile? Especially when replying, there will be 4 buttons down there!
> 
>     2. How about custom emojis? Shouldn't that also be accounted for?

It shouldn't look bad on mobile, Fractal also has four buttons in composer and without showing scrollbar is able to store the same amount of characters as gtkcord (20 letters).
Screenshot from 2023-10-01 14-07-23

Also, custom emojis should be accounted, but for now I think that bare `gtk.EmojiChooser` should be sufficient, as this is the only way mobile users can put emojis in message (without using external programs or mouse).

**Comment by diamondburned** [comment]
> this is the only way mobile users can put emojis in message (without using external programs or mouse).

That's interesting. I would've expected holding the input bar to work.

**Review by diamondburned — APPROVED** [review]

**Comment by diamondburned** [comment]
Is this PR ready to be merged?

**Comment by tfuxu** [comment]
> Is this PR ready to be merged?

Yes

**Pull request merged**
